version: '3'
services:
  qbittorrentvpn:
    build: .
    container_name: qbittorrentvpn
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
    environment:
      - VPN_ENABLED=${VPN_ENABLED}
      - VPN_TYPE=${VPN_TYPE}
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=${NAME_SERVERS}
    ports:
      - "8282:8080"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
